"""add phone number1

Revision ID: 6fc86b8361a9
Revises: a0673ba6313b
Create Date: 2023-09-28 23:37:19.453827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc86b8361a9'
down_revision = 'a0673ba6313b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('posts', 'id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True,
    #            autoincrement=True)
    # op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###
    op.add_column('users', sa.Column('phone_number',sa.String(),nullable=True))


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_column('users', 'phone_number')
#     op.alter_column('posts', 'id',
#                existing_type=sa.INTEGER(),
#                nullable=False,
#                autoincrement=True)
#     # ### end Alembic commands ###

def downgrade() -> None:
    op.drop_column('users', 'phone_number')